name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: acrpipelinedemo.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image
        run: |
          docker build -t acrpipelinedemo.azurecr.io/demo-app:${{ github.sha }} .

      - name: Push image
        run: |
          docker push acrpipelinedemo.azurecr.io/demo-app:${{ github.sha }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: DV1-321/env-config
          token: ${{ secrets.GITOPS_PAT }}
          path: env-config

      - name: Update image tag
        run: |
          sed -i "s|image: .*$|image: acrpipelinedemo.azurecr.io/demo-app:${{ github.sha }}|" env-config/overlays/prod/patch-deployment.yaml

      - name: Commit and push
        run: |
          cd env-config
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push